theme: jekyll-theme-time-machine

plugins:
  - jekyll-seo-tag
  
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /FacebookLogo.png
      author: Alexander Bisset

social:
  name: Family Tree Analyzer
  links:
    - https://www.facebook.com/ftanalyzer

description: Use FTAnalyzer to investigate your family tree in new and interesting ways, see where your ancestors lived and moved over time on the new maps feature. Find errors in your tree eg: childrens birthdates before parent was born. See lists of who is missing from census searches then click their name to automatically search on Ancestry, Find My Past, Familysearch etc. And lots more.
